Fixing CI script for pull request (#27)
* Fixing CI script for pull request

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -26,20 +26,17 @@ jobs:
       run: |
         echo "Run triggered by: ${GITHUB_EVENT_NAME}"
         if [ $(git --no-pager diff HEAD HEAD~1 --name-only | grep -v -E '^\.' | cut -d'/' -f1 | uniq | wc -l | xargs) -gt 0 ]; then
+          git --no-pager diff HEAD HEAD~1 --name-only | grep -v -E '^\.' | grep -E '\/' | cut -d'/' -f1 | uniq | xargs echo -n | jq -Rsc 'split(" ") | { "addons": (.) }' > .github/resources/addons.json      
           echo "build=yes" >> $GITHUB_OUTPUT
         else
-          if [[ ${GITHUB_EVENT_NAME} == 'workflow_dispatch' ]]; then
+          if [[ ${GITHUB_EVENT_NAME} == 'workflow_dispatch' || ${GITHUB_EVENT_NAME} == 'pull_request' ]]; then
             echo "build=yes" >> $GITHUB_OUTPUT
+            ls -d */ | cut -d'/' -f1 | uniq | xargs echo -n | jq -Rsc 'split(" ") | { "addons": (.) }' > .github/resources/addons.json
           else
             echo "build=no" >> $GITHUB_OUTPUT
           fi
         fi
 
-        if ! [[ ${GITHUB_EVENT_NAME} == 'workflow_dispatch' ]]; then
-          git --no-pager diff HEAD HEAD~1 --name-only | grep -v -E '^\.' | grep -E '\/' | cut -d'/' -f1 | uniq | xargs echo -n | jq -Rsc 'split(" ") | { "addons": (.) }' > .github/resources/addons.json
-        else
-          ls -d */ | cut -d'/' -f1 | uniq | xargs echo -n | jq -Rsc 'split(" ") | { "addons": (.) }' > .github/resources/addons.json
-        fi
         build_matrix=$(jq -sc '.[0] * .[1]' .github/resources/addons.json .github/resources/platforms.json)
         echo "build_matrix=${build_matrix}" >> $GITHUB_OUTPUT
         echo "push_matrix=$(cat .github/resources/addons.json)" >> $GITHUB_OUTPUT
@@ -187,11 +184,19 @@ jobs:
     needs: 
       - Build
       - Shared-Manifest
+      - Setup
     steps:
       - run: |
-          result="${{ needs.Build.result }}"
-          if [[ $result == "success" || $result == "skipped" ]]; then
-            exit 0
+          if [[ "${{ needs.Setup.outputs.build }}" == 'yes' ]]; then
+            result="${{ needs.Build.result }}"
+            if [[ $result == "success" || $result == "skipped" ]]; then
+              echo "Build successfull!"
+              exit 0
+            else
+              echo "Build failed!"
+              exit 1
+            fi
           else
+            echo "Did not build!"
             exit 1
           fi
